import type { AppProps } from "next/app";
import { useEffect } from "react";

import Header from "<redux>/components/includes/header";
import Footer from "<redux>/components/includes/footer";

import "<redux>/styles/globals.css";
import "<redux>/styles/header.css";
import "<redux>/styles/footer.css";
import "<redux>/styles/main.css";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  // This will scroll viewing window to top instantly on refresh or visit.
  useEffect(() => {
    const handleBeforeUnload = () => {
      window.scrollTo(0, 0);
    };
    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => {
      window.removeEventListener("beforeunload", handleBeforeUnload);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Frederick Go Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Component {...pageProps} />
      <Footer></Footer>
    </>
  );
}
